### ISSUE TITLE
Static content compilation failed after upgrade to 2.9.0 

### ISSUE THREAD

**Issue by v-rizun** [breezefront/theme-frontend-breeze-blank#10]
After update modules and theme to latest version (v2.9.0 related to Breeze Blank theme) next error appear during static-content generation attempt. If downgrade version of "swissup/breeze-blank" to 2.8.5 issue dissapears

> Compilation from source: /vendor/swissup/theme-frontend-breeze-blank/web/css/deferred-default.less
> error evaluating function `rgba` color functions take numbers as parameters index: 1835
> 
> Error happened during deploy process: Magento\Framework\Exception\LocalizedException::__construct(): Argument #1 ($phrase) must be of type Magento\Framework\Phrase, string given, called in vendor/mage-os/module-deploy/Service/DeployPackage.php on line 142
